/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'myg' at '16-9-21 下午8:20' with Gradle 2.14.1
 *
 * @author myg, @date 16-9-21 下午8:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
